const SCALE_OPTIONS={
  sleep:[["😫","Awful"],["😟","Restless"],["😐","Okay"],["😊","Good"],["🤩","Amazing"]],
  energy:[["🥵","Very low"],["😟","Low"],["😐","Okay"],["😊","Good"],["🤩","Amazing"]],
  mood:[["😭","Overwhelmed"],["😟","Anxious"],["😐","Okay"],["🙂","Calm"],["😊","Happy"]],
  pain:[["😭","Very severe"],["😣","Severe"],["😐","Moderate"],["🙂","Mild"],["😌","No pain"]]
};
const JOURNAL_ORDER=["sleep","energy","mood","pain","spoons","water","selfcare","supports"];

function journalDate(){return data.journalSelectedDate||today()}
function dateLabel(value){return new Date(value+"T12:00:00").toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function emptyJournalEntry(){return {sleep:null,energy:null,mood:null,pain:null,spoons:0,water:0,selfCare:[],supports:[],savedAt:""}}
function renderScale(name,value){return `<div class="scale">${SCALE_OPTIONS[name].map((x,i)=>`<button type="button" data-scale="${name}" data-value="${i}" class="${value!==null&&value!==undefined&&Number(value)===i?"active":""}"><span class="face">${x[0]}</span><small>${x[1]}</small></button>`).join("")}</div>`}

function journalTabs(active){return `<div class="journal-tabs"><button type="button" data-journal-tab="today" class="${active==="today"?"active":""}">Today</button><button type="button" data-journal-tab="history" class="${active==="history"?"active":""}">History</button><button type="button" data-journal-tab="trends" class="${active==="trends"?"active":""}">Trends</button></div>`}

function JournalPage(){
  data.journalTab=data.journalTab||"today";
  if(data.journalTab==="history") return JournalHistoryPage();
  if(data.journalTab==="trends") return JournalTrendsPage();
  const selected=journalDate();
  const entry={...emptyJournalEntry(),...(data.checkins[selected]||{})};
  const care=Array.isArray(data.selfCareOptions)&&data.selfCareOptions.length?data.selfCareOptions:["Rest","Reading","Exercises","Warmth","Good food","Fresh air","Music","Gaming","Hobbies"];
  const supportChoices=Array.isArray(data.supportOptions)&&data.supportOptions.length?data.supportOptions:["Left knee","Right knee","Left ankle","Right ankle","Walking stick","Other"];
  const blocks={
    sleep:`<section class="journal-section draggable" data-block="sleep" data-group="emoji"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="sleep">👁️</button><div class="section-heading"><span>😴</span><div><h2>Sleep last night</h2><p>How restorative did it feel?</p></div></div>${renderScale("sleep",entry.sleep)}</section>`,
    energy:`<section class="journal-section draggable" data-block="energy" data-group="emoji"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="energy">👁️</button><div class="section-heading"><span>⚡</span><div><h2>Energy</h2><p>How much energy do you have?</p></div></div>${renderScale("energy",entry.energy)}</section>`,
    mood:`<section class="journal-section draggable" data-block="mood" data-group="emoji"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="mood">👁️</button><div class="section-heading"><span>💜</span><div><h2>Mood</h2><p>How are you feeling emotionally?</p></div></div>${renderScale("mood",entry.mood)}</section>`,
    pain:`<section class="journal-section draggable" data-block="pain" data-group="emoji"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="pain">👁️</button><div class="section-heading"><span>☀️</span><div><h2>Pain</h2><p>How manageable is your pain?</p></div></div>${renderScale("pain",entry.pain)}</section>`,
    spoons:`<section class="journal-section draggable" data-block="spoons" data-group="wellness"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="spoons">👁️</button><div class="section-heading"><span>🥄</span><div><h2>Spoon bank</h2><p>Tap how many spoons you have used.</p></div></div><div class="tokens">${Array.from({length:12},(_,i)=>`<button type="button" class="token ${i<entry.spoons?"active":""}" data-token="spoons" data-value="${i+1}">🥄</button>`).join("")}</div></section>`,
    water:`<section class="journal-section draggable" data-block="water" data-group="wellness"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="water">👁️</button><div class="section-heading"><span>💧</span><div><h2>Water</h2><p>Glasses or bottles today.</p></div></div><div class="tokens">${Array.from({length:10},(_,i)=>`<button type="button" class="token ${i<entry.water?"active":""}" data-token="water" data-value="${i+1}">💧</button>`).join("")}</div></section>`,
    selfcare:`<section class="journal-section draggable" data-block="selfcare" data-group="wellness"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="selfcare">👁️</button><div class="section-heading section-heading-actions"><span>🌸</span><div><h2>Self-care</h2><p>Anything kind you did for yourself.</p></div><button type="button" class="mini-action" id="editSelfCare">✏️ Edit</button></div><div class="pills" id="selfCarePills">${care.map(x=>`<button type="button" class="pill ${entry.selfCare.includes(x)?"active":""}" data-care="${esc(x)}">${esc(x)}</button>`).join("")}</div><div class="compact-option-editor" id="selfCareEditor" hidden><div class="add-option-row"><input class="field" id="newCareOption" placeholder="Add another self-care option"><button type="button" class="secondary" id="addCareOption">＋ Add</button></div><div class="manage-option-list">${care.map(x=>`<div class="manage-option-chip" data-manage-care="${esc(x)}"><span>${esc(x)}</span><button type="button" class="edit-care-option" aria-label="Rename ${esc(x)}">✏️</button><button type="button" class="remove-care-option" aria-label="Remove ${esc(x)}">×</button></div>`).join("")}</div><small class="editor-hint">Use the pencil to rename an option, or × to remove it.</small></div></section>`,
    supports:`<section class="journal-section draggable" data-block="supports" data-group="wellness"><div class="drag-handle">⋮⋮</div><button type="button" class="visibility-toggle" data-visibility="supports">👁️</button><div class="section-heading"><span>🦴</span><div><h2>Braces & supports</h2><p>Select each support you used today.</p></div></div><div class="support-picker"><select class="field" id="supportSelect"><option value="">Choose a support…</option>${supportChoices.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")}</select><button type="button" class="secondary" id="addSupport">Add</button></div><div class="support-other" id="supportOther" hidden><input class="field" id="supportOtherText" placeholder="Type another brace or support"><button type="button" class="secondary" id="addOtherSupport">Add other</button></div><div class="selected-supports" id="selectedSupports">${(entry.supports||[]).map(v=>`<button type="button" class="selected-support" data-support="${esc(v)}"><span>${esc(v)}</span><b>×</b></button>`).join("")}</div></section>`
  };
  let order=(data.checkinLayout||JOURNAL_ORDER).filter(k=>blocks[k]);
  JOURNAL_ORDER.forEach(k=>{if(!order.includes(k)) order.push(k)});
  order=order.filter(k=>k!=="sleep");order.unshift("sleep");
  const rendered=order.map(k=>{const hidden=(data.checkinHidden||[]).includes(k);return blocks[k].replace('class="journal-section draggable"',`class="journal-section draggable ${hidden?"soft-hidden":""}"`)}).join("");
  const editingPast=selected!==today();
  return shell(`${head("Journal","A gentle daily check-in")}${journalTabs("today")}
    <section class="journal-date-bar"><div><span>${editingPast?"Editing past entry":"Today"}</span><strong>${dateLabel(selected)}</strong></div>${editingPast?`<button type="button" class="secondary" id="returnToday">Return to today</button>`:""}</section>
    <section class="card filter-card"><div class="layout-toolbar"><button type="button" class="collapse-title" id="toggleJournalControls"><span><h2>Journal view</h2><p>${data.journalControlsCollapsed?"Tap to customise your check-in":"Choose and rearrange what appears."}</p></span><b>${data.journalControlsCollapsed?"⌄":"⌃"}</b></button>${data.journalControlsCollapsed?"":`<button type="button" class="magic-edit ${data.checkinEditMode?"active":""}" id="toggleEditMode">${data.checkinEditMode?"✓ Done":"🪄 Edit layout"}</button>`}</div>${data.journalControlsCollapsed?"":`<div class="pills"><button type="button" class="pill ${data.checkinFilter==="all"?"active":""}" data-filter="all">Everything</button><button type="button" class="pill ${data.checkinFilter==="emoji"?"active":""}" data-filter="emoji">Check-ins</button><button type="button" class="pill ${data.checkinFilter==="wellness"?"active":""}" data-filter="wellness">Wellness</button></div>`}</section>
    <div class="journal-stack ${data.checkinEditMode?"editing":""}" id="journalStack">${rendered}</div>
    <button type="button" class="primary journal-save" id="saveJournal">Save ${editingPast?"this entry":"today’s check-in"}</button>`,"journal");
}

function JournalHistoryPage(){
  const dates=Object.keys(data.checkins||{}).sort().reverse();
  return shell(`${head("Journal","Review or complete an earlier day")}${journalTabs("history")}
    <section class="card history-picker"><span class="section-kicker">📅 Add or edit an entry</span><h2>Choose any date</h2><p>You can fill in a missed check-in after midnight or correct one later.</p><div class="date-control"><input id="journalHistoryDate" type="date" max="${today()}" value="${data.journalSelectedDate||today()}"></div><button type="button" class="primary" id="openHistoryDate">Open journal</button></section>
    <section class="journal-history-list"><div class="section-row"><div><span class="section-kicker">History</span><h2>Recent check-ins</h2></div><span>${dates.length} entries</span></div>${dates.length?dates.map(date=>{const e=data.checkins[date]||{};const count=[e.sleep,e.energy,e.mood,e.pain].filter(v=>v!==null&&v!==undefined).length;return `<button type="button" class="history-entry" data-history-date="${date}"><div><strong>${dateLabel(date)}</strong><small>${count===4?"Complete check-in":count?`${count} of 4 feelings logged`:"Wellness only"}</small></div><div class="history-faces"><span>${e.sleep!=null?SCALE_OPTIONS.sleep[e.sleep][0]:"·"}</span><span>${e.energy!=null?SCALE_OPTIONS.energy[e.energy][0]:"·"}</span><span>${e.mood!=null?SCALE_OPTIONS.mood[e.mood][0]:"·"}</span><span>${e.pain!=null?SCALE_OPTIONS.pain[e.pain][0]:"·"}</span></div><b>›</b></button>`}).join(""):`<section class="empty-state">Your saved check-ins will appear here.</section>`}</section>`,"journal");
}

function periodDays(period){return period==="week"?7:period==="month"?30:period==="six"?183:365}
function trendData(key,days){const out=[];const now=new Date();for(let i=days-1;i>=0;i--){const d=new Date(now);d.setDate(d.getDate()-i);const keyDate=d.toISOString().slice(0,10);const v=data.checkins?.[keyDate]?.[key];if(v!==null&&v!==undefined) out.push({date:keyDate,value:Number(v)})}return out}
function trendChart(key,label,period){const points=trendData(key,periodDays(period));const avg=points.length?(points.reduce((a,b)=>a+b.value,0)/points.length):null;const width=300,height=92,pad=10;const coords=points.map((p,i)=>`${points.length===1?width/2:pad+i*(width-pad*2)/(points.length-1)},${height-pad-(p.value/4)*(height-pad*2)}`).join(" ");return `<article class="trend-card"><div class="trend-head"><div><span>${key==="sleep"?"😴":key==="energy"?"⚡":key==="mood"?"💜":"☀️"}</span><strong>${label}</strong></div><span>${avg===null?"No data":`${SCALE_OPTIONS[key][Math.round(avg)][0]} ${avg.toFixed(1)} average`}</span></div>${points.length?`<svg class="trend-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${label} trend with ${points.length} entries"><line x1="10" y1="82" x2="290" y2="82"></line><line x1="10" y1="46" x2="290" y2="46"></line><line x1="10" y1="10" x2="290" y2="10"></line><polyline points="${coords}"></polyline>${points.map((p,i)=>{const x=points.length===1?width/2:pad+i*(width-pad*2)/(points.length-1),y=height-pad-(p.value/4)*(height-pad*2);return `<circle cx="${x}" cy="${y}" r="3"></circle>`}).join("")}</svg><small>${points.length} recorded ${points.length===1?"day":"days"}</small>`:`<div class="trend-empty">Save a few check-ins to see this trend.</div>`}</article>`}
function JournalTrendsPage(){const period=data.journalTrendPeriod||"week";return shell(`${head("Journal","See how things change over time")}${journalTabs("trends")}<div class="trend-periods"><button type="button" data-period="week" class="${period==="week"?"active":""}">Week</button><button type="button" data-period="month" class="${period==="month"?"active":""}">Month</button><button type="button" data-period="six" class="${period==="six"?"active":""}">6 months</button><button type="button" data-period="year" class="${period==="year"?"active":""}">Year</button></div><section class="trend-grid">${trendChart("sleep","Sleep",period)}${trendChart("energy","Energy",period)}${trendChart("mood","Mood",period)}${trendChart("pain","Pain",period)}</section><p class="trend-note">These charts show patterns in your own entries. They do not diagnose causes.</p>`,"journal")}

function bindJournal(){
 document.querySelectorAll("[data-journal-tab]").forEach(btn=>btn.onclick=()=>{data.journalTab=btn.dataset.journalTab;if(data.journalTab==="today")data.journalSelectedDate=today();saveData();render()});
 document.querySelector("#returnToday")?.addEventListener("click",()=>{data.journalSelectedDate=today();saveData();render()});
 document.querySelector("#openHistoryDate")?.addEventListener("click",()=>{const v=document.querySelector("#journalHistoryDate")?.value;if(!v)return;data.journalSelectedDate=v;data.journalTab="today";saveData();render()});
 document.querySelectorAll("[data-history-date]").forEach(btn=>btn.onclick=()=>{data.journalSelectedDate=btn.dataset.historyDate;data.journalTab="today";saveData();render()});
 document.querySelectorAll("[data-period]").forEach(btn=>btn.onclick=()=>{data.journalTrendPeriod=btn.dataset.period;saveData();render()});
 document.querySelectorAll("[data-scale]").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(`[data-scale="${btn.dataset.scale}"]`).forEach(x=>x.classList.remove("active"));btn.classList.add("active")});
 document.querySelectorAll("[data-token]").forEach(btn=>btn.onclick=()=>{const n=Number(btn.dataset.value),name=btn.dataset.token;document.querySelectorAll(`[data-token="${name}"]`).forEach(x=>x.classList.toggle("active",Number(x.dataset.value)<=n))});
 document.querySelectorAll("[data-care]").forEach(btn=>btn.onclick=()=>btn.classList.toggle("active"));
 document.querySelector("#editSelfCare")?.addEventListener("click",()=>{const editor=document.querySelector("#selfCareEditor"),button=document.querySelector("#editSelfCare");editor.hidden=!editor.hidden;button.textContent=editor.hidden?"✏️ Edit":"✓ Done";if(!editor.hidden)document.querySelector("#newCareOption")?.focus()});
 const addCareOption=()=>{const input=document.querySelector("#newCareOption"),value=String(input?.value||"").trim();if(!value)return;const options=Array.isArray(data.selfCareOptions)&&data.selfCareOptions.length?[...data.selfCareOptions]:["Rest","Reading","Exercises","Warmth","Good food","Fresh air","Music","Gaming","Hobbies"];if(options.some(x=>x.toLowerCase()===value.toLowerCase())){toast("That option is already there");return}data.selfCareOptions=[...options,value];saveData();render()};
 document.querySelector("#addCareOption")?.addEventListener("click",addCareOption);
 document.querySelector("#newCareOption")?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();addCareOption()}});
 document.querySelector("#selfCareEditor")?.addEventListener("click",e=>{const chip=e.target.closest("[data-manage-care]");if(!chip)return;const oldValue=chip.dataset.manageCare,options=Array.isArray(data.selfCareOptions)&&data.selfCareOptions.length?[...data.selfCareOptions]:["Rest","Reading","Exercises","Warmth","Good food","Fresh air","Music","Gaming","Hobbies"];
   if(e.target.closest(".remove-care-option")){if(options.length<=1){toast("Keep at least one self-care option");return}data.selfCareOptions=options.filter(x=>x!==oldValue);saveData();render();return}
   if(e.target.closest(".edit-care-option")){const next=prompt("Rename this self-care option:",oldValue);if(next===null)return;const value=next.trim();if(!value||value===oldValue)return;if(options.some(x=>x!==oldValue&&x.toLowerCase()===value.toLowerCase())){toast("That option is already there");return}data.selfCareOptions=options.map(x=>x===oldValue?value:x);Object.values(data.checkins||{}).forEach(item=>{if(Array.isArray(item.selfCare))item.selfCare=item.selfCare.map(x=>x===oldValue?value:x)});saveData();render()}
 });
 const refreshSupportOther=()=>{const select=document.querySelector("#supportSelect"),other=document.querySelector("#supportOther");if(other)other.hidden=select?.value!=="Other"};
 document.querySelector("#supportSelect")?.addEventListener("change",refreshSupportOther);
 const addSelectedSupport=value=>{value=String(value||"").trim();if(!value)return;const list=document.querySelector("#selectedSupports");const existing=[...list.querySelectorAll("[data-support]")].map(x=>x.dataset.support);if(existing.includes(value)){toast("That support is already selected");return}const btn=document.createElement("button");btn.type="button";btn.className="selected-support";btn.dataset.support=value;btn.innerHTML=`<span>${esc(value)}</span><b>×</b>`;list.appendChild(btn)};
 document.querySelector("#addSupport")?.addEventListener("click",()=>{const select=document.querySelector("#supportSelect");if(!select?.value)return;if(select.value==="Other"){refreshSupportOther();document.querySelector("#supportOtherText")?.focus();return}addSelectedSupport(select.value);select.value="";refreshSupportOther()});
 document.querySelector("#addOtherSupport")?.addEventListener("click",()=>{const input=document.querySelector("#supportOtherText");addSelectedSupport(input?.value);if(input)input.value=""});
 document.querySelector("#selectedSupports")?.addEventListener("click",e=>e.target.closest("[data-support]")?.remove());
 document.querySelectorAll("[data-filter]").forEach(btn=>btn.onclick=()=>{data.checkinFilter=btn.dataset.filter;saveData();applyJournalFilter();document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter===data.checkinFilter))});
 document.querySelector("#toggleJournalControls")?.addEventListener("click",()=>{data.journalControlsCollapsed=!data.journalControlsCollapsed;saveData();render()});
 document.querySelector("#toggleEditMode")?.addEventListener("click",()=>{if(data.checkinEditMode)saveJournalLayoutFromDom();data.checkinEditMode=!data.checkinEditMode;saveData();render()});
 document.querySelectorAll("[data-visibility]").forEach(btn=>btn.onclick=e=>{e.stopPropagation();const id=btn.dataset.visibility;data.checkinHidden=data.checkinHidden||[];data.checkinHidden=data.checkinHidden.includes(id)?data.checkinHidden.filter(x=>x!==id):[...data.checkinHidden,id];saveData();render()});
 setupJournalDrag();applyJournalFilter();document.querySelector("#saveJournal")?.addEventListener("click",saveJournalEntry);
}
function applyJournalFilter(){const filter=data.checkinFilter||"all",editing=!!data.checkinEditMode;document.querySelectorAll(".draggable").forEach(card=>{const hidden=(data.checkinHidden||[]).includes(card.dataset.block),filtered=filter!=="all"&&card.dataset.group!==filter;card.classList.toggle("filtered-out",!editing&&(hidden||filtered));card.classList.toggle("soft-hidden",editing&&hidden)})}
function saveJournalLayoutFromDom(){const stack=document.querySelector("#journalStack");if(!stack)return;const order=[...stack.querySelectorAll(".draggable")].map(c=>c.dataset.block).filter(Boolean);if(order.length){data.checkinLayout=order;saveData()}}
function setupJournalDrag(){const stack=document.querySelector("#journalStack");if(!stack||!data.checkinEditMode)return;let dragged=null;stack.querySelectorAll(".draggable").forEach(card=>{const handle=card.querySelector(".drag-handle");if(!handle)return;handle.onpointerdown=e=>{e.preventDefault();dragged=card;card.classList.add("dragging");handle.setPointerCapture?.(e.pointerId)};handle.onpointermove=e=>{if(!dragged)return;const next=[...stack.querySelectorAll(".draggable:not(.dragging)")].find(c=>e.clientY<c.getBoundingClientRect().top+c.offsetHeight/2);next?stack.insertBefore(dragged,next):stack.appendChild(dragged)};handle.onpointerup=()=>{if(!dragged)return;dragged.classList.remove("dragging");dragged=null;saveJournalLayoutFromDom()}})}
function saveJournalEntry(){const getScale=name=>{const el=document.querySelector(`[data-scale="${name}"].active`);return el?Number(el.dataset.value):null};const date=journalDate();data.checkins[date]={sleep:getScale("sleep"),energy:getScale("energy"),mood:getScale("mood"),pain:getScale("pain"),spoons:document.querySelectorAll('[data-token="spoons"].active').length,water:document.querySelectorAll('[data-token="water"].active').length,selfCare:[...document.querySelectorAll("[data-care].active")].map(x=>x.dataset.care),supports:[...document.querySelectorAll("#selectedSupports [data-support]")].map(x=>x.dataset.support).filter(Boolean),savedAt:new Date().toISOString()};saveData();toast(date===today()?"Today’s check-in saved 💜":"Past entry saved 💜")}
