const SCALE_OPTIONS={
  sleep:[["😫","Awful"],["😟","Restless"],["😐","Okay"],["😊","Good"],["🤩","Amazing"]],
  energy:[["🥵","Very low"],["😟","Low"],["😐","Okay"],["😊","Good"],["🤩","Amazing"]],
  mood:[["😭","Stressed"],["😟","Anxious"],["😐","Okay"],["🙂","Calm"],["😊","Happy"]],
  pain:[["😭","Very severe"],["😣","Severe"],["😐","Moderate"],["🙂","Mild"],["😌","No pain"]]
};
const JOURNAL_ORDER=["energy","mood","pain","spoons","water","selfcare","supports"];

function journalDate(){return data.journalSelectedDate||today()}
function dateLabel(value){return new Date(value+"T12:00:00").toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function emptyJournalEntry(){return {sleep:null,energy:null,mood:null,pain:null,spoons:0,water:0,selfCare:[],supports:[],savedAt:""}}
function renderScale(name,value){return `<div class="scale">${SCALE_OPTIONS[name].map((x,i)=>`<button type="button" data-scale="${name}" data-value="${i}" class="${value!==null&&value!==undefined&&Number(value)===i?"active":""}"><span class="face">${x[0]}</span><small>${x[1]}</small></button>`).join("")}</div>`}

function journalTabs(active){return `<div class="journal-tabs"><button type="button" data-journal-tab="today" class="${active==="today"?"active":""}">Today</button><button type="button" data-journal-tab="history" class="${active==="history"?"active":""}">History</button><button type="button" data-journal-tab="trends" class="${active==="trends"?"active":""}">Trends</button></div>`}

function JournalPage(){
  data.journalTab=data.journalTab||"today";
  if(data.journalTab==="history") return JournalHistoryPage();
  if(data.journalTab==="trends") return JournalTrendsPage();
  data.dayCheckins=Array.isArray(data.dayCheckins)?data.dayCheckins:[];
  const dateValue=today();
  const entries=typeof dayEntries==="function"?dayEntries(dateValue):data.dayCheckins.filter(entry=>entry.date===dateValue).sort((a,b)=>String(a.createdAt||"").localeCompare(String(b.createdAt||"")));
  return shell(`${head("Journal","Small check-ins throughout your day")}${journalTabs("today")}
    <section class="card hourly-journal-hero">
      <div><span class="section-kicker">✨ Hourly journal</span><h2>How are you right now?</h2><p>Add a quick energy, mood and pain check-in whenever the hour changes. You can also leave a short note.</p></div>
      <button type="button" class="primary" data-open-hourly-checkin>＋ Add check-in</button>
    </section>
    <section class="card journey-card"><div class="section-title"><div><span class="section-kicker">Today</span><h2>Journal timeline</h2></div><strong>${entries.length} check-in${entries.length===1?"":"s"}</strong></div><div class="journey-timeline ${entries.length?"":"empty-journey"}">${entries.length?entries.map(journeyEntry).join(""):`<div class="journey-empty"><span>✨</span><strong>No check-ins yet</strong><small>Your first hourly check-in will appear here.</small></div>`}</div></section>`,"journal");
}

function JournalHistoryPage(){
  const dates=Object.keys(data.checkins||{}).sort().reverse();
  return shell(`${head("Journal","Review or complete an earlier day")}${journalTabs("history")}
    <section class="card history-picker"><span class="section-kicker">📅 Add or edit an entry</span><h2>Choose any date</h2><p>You can fill in a missed check-in after midnight or correct one later.</p><div class="date-control"><input id="journalHistoryDate" type="date" max="${today()}" value="${data.journalSelectedDate||today()}"></div><button type="button" class="primary" id="openHistoryDate">Open journal</button></section>
    <section class="journal-history-list"><div class="section-row"><div><span class="section-kicker">History</span><h2>Recent check-ins</h2></div><span>${dates.length} entries</span></div>${dates.length?dates.map(date=>{const e=data.checkins[date]||{};const count=[e.sleep,e.energy,e.mood,e.pain].filter(v=>v!==null&&v!==undefined).length;return `<button type="button" class="history-entry" data-history-date="${date}"><div><strong>${dateLabel(date)}</strong><small>${count===4?"Complete check-in":count?`${count} of 4 feelings logged`:"Wellness only"}</small></div><div class="history-faces"><span>${e.sleep!=null?SCALE_OPTIONS.sleep[e.sleep][0]:"·"}</span><span>${e.energy!=null?SCALE_OPTIONS.energy[e.energy][0]:"·"}</span><span>${e.mood!=null?SCALE_OPTIONS.mood[e.mood][0]:"·"}</span><span>${e.pain!=null?SCALE_OPTIONS.pain[e.pain][0]:"·"}</span></div><b>›</b></button>`}).join(""):`<section class="empty-state">Your saved check-ins will appear here.</section>`}</section>`,"journal");
}

function periodDays(period){return period==="week"?7:period==="month"?30:period==="six"?183:365}
function trendData(key,days){const out=[];const now=new Date();for(let i=days-1;i>=0;i--){const d=new Date(now);d.setDate(d.getDate()-i);const keyDate=d.toISOString().slice(0,10);const v=data.checkins?.[keyDate]?.[key];if(v!==null&&v!==undefined) out.push({date:keyDate,value:Number(v)})}return out}
function trendChart(key,label,period){const points=trendData(key,periodDays(period));const avg=points.length?(points.reduce((a,b)=>a+b.value,0)/points.length):null;const width=300,height=92,pad=10;const coords=points.map((p,i)=>`${points.length===1?width/2:pad+i*(width-pad*2)/(points.length-1)},${height-pad-(p.value/4)*(height-pad*2)}`).join(" ");return `<article class="trend-card"><div class="trend-head"><div><span>${key==="sleep"?"😴":key==="energy"?"⚡":key==="mood"?"💜":"☀️"}</span><strong>${label}</strong></div><span>${avg===null?"No data":`${SCALE_OPTIONS[key][Math.round(avg)][0]} ${avg.toFixed(1)} average`}</span></div>${points.length?`<svg class="trend-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${label} trend with ${points.length} entries"><line x1="10" y1="82" x2="290" y2="82"></line><line x1="10" y1="46" x2="290" y2="46"></line><line x1="10" y1="10" x2="290" y2="10"></line><polyline points="${coords}"></polyline>${points.map((p,i)=>{const x=points.length===1?width/2:pad+i*(width-pad*2)/(points.length-1),y=height-pad-(p.value/4)*(height-pad*2);return `<circle cx="${x}" cy="${y}" r="3"></circle>`}).join("")}</svg><small>${points.length} recorded ${points.length===1?"day":"days"}</small>`:`<div class="trend-empty">Save a few check-ins to see this trend.</div>`}</article>`}
function JournalTrendsPage(){const period=data.journalTrendPeriod||"week";return shell(`${head("Journal","See how things change over time")}${journalTabs("trends")}<div class="trend-periods"><button type="button" data-period="week" class="${period==="week"?"active":""}">Week</button><button type="button" data-period="month" class="${period==="month"?"active":""}">Month</button><button type="button" data-period="six" class="${period==="six"?"active":""}">6 months</button><button type="button" data-period="year" class="${period==="year"?"active":""}">Year</button></div><section class="trend-grid">${trendChart("energy","Energy",period)}${trendChart("mood","Mood",period)}${trendChart("pain","Pain",period)}</section><p class="trend-note">These charts show patterns in your own entries. They do not diagnose causes.</p>`,"journal")}

function bindJournal(){
 document.querySelectorAll("[data-journal-tab]").forEach(btn=>btn.onclick=()=>{data.journalTab=btn.dataset.journalTab;if(data.journalTab==="today")data.journalSelectedDate=today();saveData();render()});
 document.querySelector("#returnToday")?.addEventListener("click",()=>{data.journalSelectedDate=today();saveData();render()});
 document.querySelector("#openHistoryDate")?.addEventListener("click",()=>{const v=document.querySelector("#journalHistoryDate")?.value;if(!v)return;data.journalSelectedDate=v;data.journalTab="today";saveData();render()});
 document.querySelectorAll("[data-history-date]").forEach(btn=>btn.onclick=()=>{data.journalSelectedDate=btn.dataset.historyDate;data.journalTab="today";saveData();render()});
 document.querySelectorAll("[data-period]").forEach(btn=>btn.onclick=()=>{data.journalTrendPeriod=btn.dataset.period;saveData();render()});
 document.querySelectorAll("[data-scale]").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(`[data-scale="${btn.dataset.scale}"]`).forEach(x=>x.classList.remove("active"));btn.classList.add("active")});
 document.querySelectorAll("[data-token]").forEach(btn=>btn.onclick=()=>{const n=Number(btn.dataset.value),name=btn.dataset.token;document.querySelectorAll(`[data-token="${name}"]`).forEach(x=>x.classList.toggle("active",Number(x.dataset.value)<=n))});
 document.querySelectorAll("[data-care]").forEach(btn=>btn.onclick=()=>btn.classList.toggle("active"));
 document.querySelector("#editSelfCare")?.addEventListener("click",()=>{const editor=document.querySelector("#selfCareEditor"),button=document.querySelector("#editSelfCare");editor.hidden=!editor.hidden;button.textContent=editor.hidden?"✏️ Edit":"✓ Done";if(!editor.hidden)document.querySelector("#newCareOption")?.focus()});
 const addCareOption=()=>{const input=document.querySelector("#newCareOption"),status=document.querySelector("#selfCareAddStatus"),value=String(input?.value||"").trim();if(!value){if(status)status.textContent="Type an option first.";input?.focus();return}const options=Array.isArray(data.selfCareOptions)&&data.selfCareOptions.length?[...data.selfCareOptions]:["Rest","Reading","Exercises","Warmth","Good food","Fresh air","Music","Gaming","Hobbies"];if(options.some(x=>x.toLowerCase()===value.toLowerCase())){if(status)status.textContent=`${value} is already in your list.`;toast("That option is already there");input?.select();return}data.selfCareOptions=[...options,value];saveData();const pills=document.querySelector("#selfCarePills"),manage=document.querySelector("#selfCareEditor .manage-option-list");if(pills){const button=document.createElement("button");button.type="button";button.className="pill";button.dataset.care=value;button.textContent=value;button.addEventListener("click",()=>button.classList.toggle("active"));pills.appendChild(button)}if(manage){const chip=document.createElement("div");chip.className="manage-option-chip";chip.dataset.manageCare=value;chip.innerHTML=`<span>${esc(value)}</span><button type="button" class="edit-care-option" aria-label="Rename ${esc(value)}">✏️</button><button type="button" class="remove-care-option" aria-label="Remove ${esc(value)}">×</button>`;manage.appendChild(chip)}if(input)input.value="";if(status)status.textContent=`${value} added.`;toast(`${value} added`);input?.focus()};
 document.querySelector("#addCareOption")?.addEventListener("click",addCareOption);
 document.querySelector("#newCareOption")?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();addCareOption()}});
 document.querySelector("#selfCareEditor")?.addEventListener("click",e=>{const chip=e.target.closest("[data-manage-care]");if(!chip)return;const oldValue=chip.dataset.manageCare,options=Array.isArray(data.selfCareOptions)&&data.selfCareOptions.length?[...data.selfCareOptions]:["Rest","Reading","Exercises","Warmth","Good food","Fresh air","Music","Gaming","Hobbies"];
   if(e.target.closest(".remove-care-option")){if(options.length<=1){toast("Keep at least one self-care option");return}data.selfCareOptions=options.filter(x=>x!==oldValue);saveData();render();return}
   if(e.target.closest(".edit-care-option")){const next=prompt("Rename this self-care option:",oldValue);if(next===null)return;const value=next.trim();if(!value||value===oldValue)return;if(options.some(x=>x!==oldValue&&x.toLowerCase()===value.toLowerCase())){toast("That option is already there");return}data.selfCareOptions=options.map(x=>x===oldValue?value:x);Object.values(data.checkins||{}).forEach(item=>{if(Array.isArray(item.selfCare))item.selfCare=item.selfCare.map(x=>x===oldValue?value:x)});saveData();render()}
 });
 const refreshSupportOther=()=>{const select=document.querySelector("#supportSelect"),other=document.querySelector("#supportOther");if(other)other.hidden=select?.value!=="Other"};
 document.querySelector("#supportSelect")?.addEventListener("change",refreshSupportOther);
 const addSelectedSupport=value=>{value=String(value||"").trim();if(!value)return;const list=document.querySelector("#selectedSupports");const existing=[...list.querySelectorAll("[data-support]")].map(x=>x.dataset.support);if(existing.includes(value)){toast("That support is already selected");return}const btn=document.createElement("button");btn.type="button";btn.className="selected-support";btn.dataset.support=value;btn.innerHTML=`<span>${esc(value)}</span><b>×</b>`;list.appendChild(btn)};
 document.querySelector("#addSupport")?.addEventListener("click",()=>{const select=document.querySelector("#supportSelect");if(!select?.value)return;if(select.value==="Other"){refreshSupportOther();document.querySelector("#supportOtherText")?.focus();return}addSelectedSupport(select.value);select.value="";refreshSupportOther()});
 document.querySelector("#addOtherSupport")?.addEventListener("click",()=>{const input=document.querySelector("#supportOtherText");addSelectedSupport(input?.value);if(input)input.value=""});
 document.querySelector("#selectedSupports")?.addEventListener("click",e=>e.target.closest("[data-support]")?.remove());
 document.querySelectorAll("[data-filter]").forEach(btn=>btn.onclick=()=>{data.checkinFilter=btn.dataset.filter;saveData();applyJournalFilter();document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter===data.checkinFilter))});
 document.querySelector("#toggleJournalControls")?.addEventListener("click",()=>{data.journalControlsCollapsed=!data.journalControlsCollapsed;saveData();render()});
 document.querySelector("#toggleEditMode")?.addEventListener("click",()=>{if(data.checkinEditMode)saveJournalLayoutFromDom();data.checkinEditMode=!data.checkinEditMode;saveData();render()});
 document.querySelectorAll("[data-visibility]").forEach(btn=>btn.onclick=e=>{e.stopPropagation();const id=btn.dataset.visibility;data.checkinHidden=data.checkinHidden||[];data.checkinHidden=data.checkinHidden.includes(id)?data.checkinHidden.filter(x=>x!==id):[...data.checkinHidden,id];saveData();render()});
 setupJournalDrag();applyJournalFilter();document.querySelector("#saveJournal")?.addEventListener("click",saveJournalEntry);
}
function applyJournalFilter(){const filter=data.checkinFilter||"all",editing=!!data.checkinEditMode;document.querySelectorAll(".draggable").forEach(card=>{const hidden=(data.checkinHidden||[]).includes(card.dataset.block),filtered=filter!=="all"&&card.dataset.group!==filter;card.classList.toggle("filtered-out",!editing&&(hidden||filtered));card.classList.toggle("soft-hidden",editing&&hidden)})}
function saveJournalLayoutFromDom(){const stack=document.querySelector("#journalStack");if(!stack)return;const order=[...stack.querySelectorAll(".draggable")].map(c=>c.dataset.block).filter(Boolean);if(order.length){data.checkinLayout=order;saveData()}}
function setupJournalDrag(){const stack=document.querySelector("#journalStack");if(!stack||!data.checkinEditMode)return;let dragged=null;stack.querySelectorAll(".draggable").forEach(card=>{const handle=card.querySelector(".drag-handle");if(!handle)return;handle.onpointerdown=e=>{e.preventDefault();dragged=card;card.classList.add("dragging");handle.setPointerCapture?.(e.pointerId)};handle.onpointermove=e=>{if(!dragged)return;const next=[...stack.querySelectorAll(".draggable:not(.dragging)")].find(c=>e.clientY<c.getBoundingClientRect().top+c.offsetHeight/2);next?stack.insertBefore(dragged,next):stack.appendChild(dragged)};handle.onpointerup=()=>{if(!dragged)return;dragged.classList.remove("dragging");dragged=null;saveJournalLayoutFromDom()}})}
function saveJournalEntry(){const getScale=name=>{const el=document.querySelector(`[data-scale="${name}"].active`);return el?Number(el.dataset.value):null};const date=journalDate();data.checkins[date]={...(data.checkins[date]||{}),energy:getScale("energy"),mood:getScale("mood"),pain:getScale("pain"),spoons:document.querySelectorAll('[data-token="spoons"].active').length,water:document.querySelectorAll('[data-token="water"].active').length,selfCare:[...document.querySelectorAll("[data-care].active")].map(x=>x.dataset.care),supports:[...document.querySelectorAll("#selectedSupports [data-support]")].map(x=>x.dataset.support).filter(Boolean),savedAt:new Date().toISOString()};saveData();toast(date===today()?"Today’s check-in saved 💜":"Past entry saved 💜")}
