const PLANT_ENCYCLOPEDIA=[
  {id:"lemon-tree",name:"Lemon Tree",scientific:"Citrus limon",emoji:"🍋",light:"Very bright light; several hours of direct sun is ideal.",water:"Water thoroughly when the top 2–3 cm of compost feels dry. Do not leave it sitting in water.",humidity:"Normal household humidity is usually fine.",temperature:"Prefers warmth; protect from cold draughts and frost.",feeding:"Citrus feed every 1–2 weeks in spring and summer; reduce in winter.",soil:"Free-draining citrus or houseplant compost with added perlite.",tips:["Turn the pot regularly for even growth.","Yellow leaves can mean overwatering, poor drainage or a nutrient shortage.","Repot only one size up when roots are crowded."],wateringDays:7},
  {id:"basil",name:"Basil",scientific:"Ocimum basilicum",emoji:"🌿",light:"Bright light with around 6 hours of sun. Shield from harsh scorching midday sun behind glass.",water:"Keep lightly and evenly moist. Water when the surface begins to feel dry.",humidity:"Average humidity; good airflow helps prevent mildew.",temperature:"Warm conditions, ideally above 15°C.",feeding:"Half-strength liquid feed every 2–4 weeks while actively growing.",soil:"Rich but free-draining multipurpose compost.",tips:["Pinch out flower buds to keep leaves tender and encourage bushy growth.","Harvest just above a pair of leaves.","Avoid leaving the roots waterlogged."],wateringDays:3},
  {id:"greek-oregano",name:"Greek Oregano",scientific:"Origanum vulgare subsp. hirtum",emoji:"🌱",light:"Full sun or the brightest window available.",water:"Allow the compost to dry noticeably between waterings.",humidity:"Prefers drier air and good airflow.",temperature:"Tolerates normal indoor temperatures; hardy outdoors in suitable conditions.",feeding:"Feed sparingly; too much fertiliser can reduce flavour.",soil:"Very free-draining compost, ideally with grit or perlite.",tips:["Trim regularly to prevent legginess.","Do not keep constantly damp.","Strong light produces the best flavour."],wateringDays:7},
  {id:"orchid",name:"Orchid",scientific:"Phalaenopsis hybrid",emoji:"🌸",light:"Bright indirect light; an east or filtered south/west window works well.",water:"Soak the bark thoroughly, then drain completely. Water again when roots look silvery and the pot feels light.",humidity:"Moderate humidity with gentle airflow.",temperature:"Normal warm indoor temperatures; avoid cold draughts.",feeding:"Weak orchid fertiliser every 2–4 waterings during active growth.",soil:"Orchid bark, never ordinary dense compost.",tips:["Healthy wet roots are green; dry roots are silvery.","Keep water out of the crown.","Trim only dead, hollow or mushy roots with clean scissors."],wateringDays:9},
  {id:"nemesia-vanilla",name:"Nemesia 'Vanilla'",scientific:"Nemesia hybrid",emoji:"🌼",light:"Full sun to bright partial shade.",water:"Keep evenly moist but not waterlogged, especially while flowering.",humidity:"Normal outdoor or household humidity with airflow.",temperature:"Prefers cooler conditions and may struggle in strong heat.",feeding:"Balanced liquid feed every 2–3 weeks while blooming.",soil:"Fertile, free-draining multipurpose compost.",tips:["Deadhead faded flowers to encourage more blooms.","Trim lightly if growth becomes straggly.","Protect the pot from drying out completely."],wateringDays:3},
  {id:"spider-plant",name:"Spider Plant",scientific:"Chlorophytum comosum",emoji:"🪴",light:"Bright indirect light, though it tolerates medium light.",water:"Water when the top few centimetres feel dry. Slight drying is safer than constant wetness.",humidity:"Average humidity; brown tips can worsen in very dry air.",temperature:"Normal indoor temperatures; avoid frost.",feeding:"Monthly half-strength feed in spring and summer.",soil:"Standard free-draining houseplant compost.",tips:["Brown tips may come from salts, dry air or irregular watering.","Plantlets can be rooted in water or compost.","It tolerates being slightly root-bound."],wateringDays:7},
  {id:"prayer-plant",name:"Prayer Plant",scientific:"Maranta leuconeura",emoji:"🍃",light:"Bright indirect light; direct sun can fade or scorch leaves.",water:"Keep lightly moist, watering when the surface just begins to dry. Use rainwater or filtered water where possible.",humidity:"Likes higher humidity.",temperature:"Warm and stable; avoid cold draughts.",feeding:"Half-strength feed monthly in spring and summer.",soil:"Moisture-retentive but airy houseplant mix with perlite.",tips:["Crispy edges often point to dry air, hard water or underwatering.","Leaves naturally fold upward at night.","Do not let the pot sit in water."],wateringDays:5},
  {id:"apple-seeds",name:"Apple Seeds",scientific:"Malus domestica",emoji:"🍎",light:"After germination, provide very bright light and gradually introduce direct sun.",water:"Keep seed compost lightly moist, never sodden.",humidity:"A covered container can help during germination, but ventilate to prevent mould.",temperature:"Seeds usually need a cold, moist stratification period before warmth.",feeding:"Do not feed until seedlings have several true leaves; then use a very weak balanced feed.",soil:"Fine seed compost initially, then free-draining potting compost.",tips:["Chill moist seeds in the fridge for roughly 6–10 weeks.","Seed-grown apples will not grow true to the parent fruit.","Remove any mouldy seeds promptly."],wateringDays:4},
  {id:"pothos",name:"Pothos",scientific:"Epipremnum aureum",emoji:"🌿",light:"Bright indirect light; tolerates lower light with slower growth.",water:"Allow the top half of the compost to dry before watering thoroughly.",humidity:"Average household humidity is fine.",temperature:"Warm indoor conditions; avoid cold draughts.",feeding:"Monthly in spring and summer at half strength.",soil:"Free-draining houseplant compost.",tips:["Prune above a node for bushier growth.","Yellow leaves often follow overwatering.","Toxic if eaten by pets or people."],wateringDays:8},
  {id:"peace-lily",name:"Peace Lily",scientific:"Spathiphyllum",emoji:"🤍",light:"Medium to bright indirect light.",water:"Water when the top 2–3 cm dries; it may droop dramatically when thirsty.",humidity:"Enjoys moderate to high humidity.",temperature:"Warm indoor temperatures away from draughts.",feeding:"Monthly weak feed in spring and summer.",soil:"Moisture-retentive but draining houseplant compost.",tips:["Wipe leaves to keep them dust-free.","Brown tips can reflect salts or dry air.","Toxic if eaten by pets or people."],wateringDays:6},
  {id:"snake-plant",name:"Snake Plant",scientific:"Dracaena trifasciata",emoji:"🌵",light:"Bright indirect light is best, but it tolerates lower light.",water:"Let the compost dry fully before watering again.",humidity:"Normal or dry household air.",temperature:"Keep above roughly 10°C.",feeding:"Light feed every 6–8 weeks in spring and summer.",soil:"Very free-draining cactus or succulent mix.",tips:["Overwatering is the main danger.","Use a pot with drainage holes.","Toxic if eaten by pets."],wateringDays:18},
  {id:"aloe-vera",name:"Aloe Vera",scientific:"Aloe barbadensis miller",emoji:"🌵",light:"Very bright light with some direct sun, introduced gradually.",water:"Soak thoroughly, then let the compost dry completely.",humidity:"Prefers dry air.",temperature:"Warm conditions; protect from frost.",feeding:"Very weak succulent feed a few times during spring and summer.",soil:"Cactus or succulent compost with excellent drainage.",tips:["Soft translucent leaves often mean too much water.","Rotate for even growth.","Use a heavy pot if the plant becomes top-heavy."],wateringDays:18},
  {id:"miniature-rose",name:"Miniature Rose",scientific:"Rosa hybrid",emoji:"🌹",light:"Full sun or the brightest window available; aim for at least 6 hours of direct light.",water:"Water thoroughly when the top 2 cm feels dry. Never leave the pot standing in water.",humidity:"Average humidity with good airflow.",temperature:"Prefers cooler bright conditions; keep away from radiators.",feeding:"Rose feed every 2 weeks while flowering.",soil:"Rich, free-draining rose or multipurpose compost.",tips:["Remove faded blooms to encourage more flowers.","A decorative vase or cover pot must not trap drainage water.","Check regularly for aphids and spider mites."],wateringDays:4},
  {id:"monstera",name:"Monstera",scientific:"Monstera deliciosa",emoji:"🌿",light:"Bright indirect light; gentle morning sun is fine.",water:"Water when the top 3–5 cm is dry.",humidity:"Average to higher humidity.",temperature:"Warm indoor temperatures away from draughts.",feeding:"Monthly in spring and summer.",soil:"Chunky free-draining aroid mix.",tips:["Give mature plants a moss pole.","Wipe large leaves regularly.","Toxic if eaten."],wateringDays:8},
  {id:"rubber-plant",name:"Rubber Plant",scientific:"Ficus elastica",emoji:"🌳",light:"Bright indirect light.",water:"Water when the upper compost has dried.",humidity:"Average humidity.",temperature:"Warm and stable; avoid sudden moves.",feeding:"Monthly in active growth.",soil:"Free-draining houseplant compost.",tips:["Wipe leaves clean.","Sap can irritate skin.","Toxic if eaten."],wateringDays:9},
  {id:"zz-plant",name:"ZZ Plant",scientific:"Zamioculcas zamiifolia",emoji:"🌿",light:"Medium to bright indirect light; tolerates low light.",water:"Let the compost dry almost completely.",humidity:"Average household humidity.",temperature:"Normal indoor warmth.",feeding:"Light feed every 6–8 weeks.",soil:"Very free-draining mix.",tips:["Overwatering is the main risk.","Growth is naturally slow.","Toxic if eaten."],wateringDays:18},
  {id:"calathea",name:"Calathea",scientific:"Goeppertia species",emoji:"🍃",light:"Bright indirect light.",water:"Keep lightly moist using rain or filtered water.",humidity:"High humidity is helpful.",temperature:"Warm and draught-free.",feeding:"Weak monthly feed in spring and summer.",soil:"Airy moisture-retentive mix.",tips:["Crispy edges often mean dry air or hard water.","Avoid direct sun.","Keep conditions consistent."],wateringDays:5},
  {id:"string-of-hearts",name:"String of Hearts",scientific:"Ceropegia woodii",emoji:"💚",light:"Very bright indirect light with some gentle sun.",water:"Allow most of the compost to dry.",humidity:"Average to dry air.",temperature:"Warm indoor temperatures.",feeding:"Weak monthly feed in growth.",soil:"Succulent-style free-draining compost.",tips:["Tuber-like beads can be pressed into compost to propagate.","Avoid a permanently wet pot.","Trim to encourage branching."],wateringDays:12},
  {id:"jade-plant",name:"Jade Plant",scientific:"Crassula ovata",emoji:"🪴",light:"Very bright light with some direct sun.",water:"Let compost dry fully before watering.",humidity:"Dry air is fine.",temperature:"Warm days and cooler nights are suitable.",feeding:"Light succulent feed in spring and summer.",soil:"Cactus and succulent compost.",tips:["Wrinkled leaves can mean thirst.","Soft leaves often mean excess water.","Use a heavy pot for stability."],wateringDays:16},
  {id:"lavender",name:"Lavender",scientific:"Lavandula angustifolia",emoji:"💜",light:"Full direct sun.",water:"Allow compost to dry between waterings.",humidity:"Prefers dry air and airflow.",temperature:"Cool to warm; hardy outdoors.",feeding:"Feed sparingly.",soil:"Very gritty free-draining compost.",tips:["Indoor lavender often struggles without enough sun.","Trim after flowering.","Never leave waterlogged."],wateringDays:7},
  {id:"rosemary",name:"Rosemary",scientific:"Salvia rosmarinus",emoji:"🌿",light:"Full sun.",water:"Water when the top few centimetres dry; drain well.",humidity:"Dry air and strong airflow.",temperature:"Cool bright conditions suit it.",feeding:"Light feed monthly in growth.",soil:"Gritty free-draining compost.",tips:["Do not let roots sit in water.","Prune lightly and regularly.","Strong light improves flavour."],wateringDays:7},
  {id:"mint",name:"Mint",scientific:"Mentha species",emoji:"🌱",light:"Bright light to partial sun.",water:"Keep evenly moist.",humidity:"Average humidity.",temperature:"Cool to warm conditions.",feeding:"Monthly feed in containers.",soil:"Rich moisture-retentive compost.",tips:["Pinch tips for bushier growth.","Best kept in its own pot.","Cut back tired growth."],wateringDays:3},
  {id:"thyme",name:"Thyme",scientific:"Thymus vulgaris",emoji:"🌿",light:"Full sun.",water:"Let compost dry well between watering.",humidity:"Dry air and airflow.",temperature:"Normal indoor or outdoor temperatures.",feeding:"Feed very lightly.",soil:"Gritty free-draining compost.",tips:["Avoid overwatering.","Trim after flowering.","Harvest regularly."],wateringDays:8},
  {id:"parsley",name:"Parsley",scientific:"Petroselinum crispum",emoji:"🌿",light:"Bright light with several hours of sun.",water:"Keep evenly moist but drained.",humidity:"Average humidity.",temperature:"Prefers cooler conditions.",feeding:"Liquid feed monthly.",soil:"Rich free-draining compost.",tips:["Harvest outer stems first.","It is naturally biennial.","Do not let seedlings dry out."],wateringDays:4},
  {id:"chives",name:"Chives",scientific:"Allium schoenoprasum",emoji:"🌱",light:"Full sun to bright light.",water:"Keep lightly moist.",humidity:"Average humidity.",temperature:"Cool to warm conditions.",feeding:"Monthly light feed.",soil:"Free-draining multipurpose compost.",tips:["Cut leaves near the base.","Remove flowers if leaf production is the priority.","Divide congested clumps."],wateringDays:4},
  {id:"succulent-mix",name:"Mixed Succulents",scientific:"Various succulent species",emoji:"🌵",light:"Very bright light, often with direct sun.",water:"Soak then dry completely.",humidity:"Dry air.",temperature:"Warm conditions; avoid frost.",feeding:"Very weak feed in spring and summer.",soil:"Cactus and succulent compost.",tips:["Different species may have slightly different needs.","Use drainage holes.","Stretching means insufficient light."],wateringDays:16},
  {id:"echeveria",name:"Echeveria",scientific:"Echeveria species",emoji:"🌵",light:"Strong light with direct sun introduced gradually.",water:"Water deeply only when fully dry.",humidity:"Dry air.",temperature:"Warm, with a cooler winter rest.",feeding:"Weak succulent feed occasionally.",soil:"Mineral-rich succulent mix.",tips:["Keep water out of the rosette.","Remove dead lower leaves.","Leggy growth means more light is needed."],wateringDays:18},
  {id:"christmas-cactus",name:"Christmas Cactus",scientific:"Schlumbergera hybrid",emoji:"🌸",light:"Bright indirect light.",water:"Water when the top layer dries; slightly less after flowering.",humidity:"Moderate humidity.",temperature:"Normal indoor warmth with cooler nights for bud formation.",feeding:"Monthly during growth.",soil:"Airy free-draining mix.",tips:["Do not move repeatedly once buds form.","It is a tropical cactus, not a desert cactus.","Repot only when crowded."],wateringDays:8},
  {id:"anthurium",name:"Anthurium",scientific:"Anthurium andraeanum",emoji:"❤️",light:"Bright indirect light.",water:"Water when the top 2–3 cm dries.",humidity:"Likes higher humidity.",temperature:"Warm and stable.",feeding:"Weak monthly feed.",soil:"Chunky aroid mix.",tips:["Keep leaves clean.","Avoid cold draughts.","Toxic if eaten."],wateringDays:7},
  {id:"african-violet",name:"African Violet",scientific:"Streptocarpus ionanthus",emoji:"🌸",light:"Bright indirect light.",water:"Water when the surface begins to dry, preferably from below.",humidity:"Moderate humidity without wet leaves.",temperature:"Warm stable temperatures.",feeding:"Specialist violet feed every 2–4 weeks.",soil:"Light airy African violet mix.",tips:["Avoid cold water on leaves.","Remove spent flowers.","A snug pot encourages blooming."],wateringDays:5},
  {id:"begonia",name:"Begonia",scientific:"Begonia hybrid",emoji:"🌺",light:"Bright indirect light.",water:"Water when the top layer dries; avoid soggy compost.",humidity:"Moderate humidity and airflow.",temperature:"Warm indoor conditions.",feeding:"Weak feed every 2–4 weeks.",soil:"Airy moisture-retentive compost.",tips:["Avoid wetting fuzzy leaves.","Pinch tips for fullness.","Watch for mildew."],wateringDays:6},
  {id:"geranium",name:"Geranium",scientific:"Pelargonium hybrid",emoji:"🌺",light:"Very bright light with direct sun.",water:"Water when the top compost dries.",humidity:"Average to dry air.",temperature:"Warm days; protect from frost.",feeding:"Flowering feed every 2 weeks.",soil:"Free-draining multipurpose compost.",tips:["Deadhead regularly.","Pinch back leggy stems.","Let the pot drain fully."],wateringDays:5},
  {id:"hydrangea",name:"Hydrangea",scientific:"Hydrangea macrophylla",emoji:"🌸",light:"Bright light or morning sun with afternoon shade.",water:"Keep evenly moist; do not allow complete drying.",humidity:"Average humidity.",temperature:"Prefers cooler conditions.",feeding:"Hydrangea feed during active growth.",soil:"Rich moisture-retentive compost.",tips:["Small gift plants often need frequent watering.","Move outdoors gradually when suitable.","Flower colour can be influenced by soil chemistry."],wateringDays:3},
  {id:"azalea",name:"Azalea",scientific:"Rhododendron simsii",emoji:"🌺",light:"Bright indirect light or cool morning sun.",water:"Keep evenly moist with rainwater where possible.",humidity:"Likes humidity.",temperature:"Cool conditions prolong flowering.",feeding:"Acid-loving plant feed after flowering.",soil:"Ericaceous compost.",tips:["Never let the root ball dry completely.","Keep away from radiators.","Toxic if eaten."],wateringDays:3},
  {id:"cyclamen",name:"Cyclamen",scientific:"Cyclamen persicum",emoji:"🌸",light:"Bright indirect light.",water:"Water from below when the compost starts to dry.",humidity:"Average humidity with airflow.",temperature:"Prefers cool rooms.",feeding:"Weak flowering feed every 2–3 weeks.",soil:"Free-draining multipurpose compost.",tips:["Avoid water in the crown.","Remove spent stems with a gentle twist.","It may become dormant after flowering."],wateringDays:4},
  {id:"poinsettia",name:"Poinsettia",scientific:"Euphorbia pulcherrima",emoji:"🌺",light:"Bright indirect light.",water:"Water when the surface dries; drain completely.",humidity:"Average humidity.",temperature:"Warm and away from cold draughts.",feeding:"Feed monthly after the coloured bracts fade.",soil:"Free-draining houseplant compost.",tips:["Cold exposure causes leaf drop.","Sap can irritate skin.","Recolouring requires controlled long nights."],wateringDays:6},
  {id:"boston-fern",name:"Boston Fern",scientific:"Nephrolepis exaltata",emoji:"🌿",light:"Bright indirect light.",water:"Keep consistently lightly moist.",humidity:"High humidity.",temperature:"Cool to normal indoor warmth.",feeding:"Weak monthly feed in growth.",soil:"Moisture-retentive airy compost.",tips:["Crispy fronds usually mean dryness.","Mist or use a humidifier.","Trim dead fronds at the base."],wateringDays:4},
  {id:"maidenhair-fern",name:"Maidenhair Fern",scientific:"Adiantum raddianum",emoji:"🌿",light:"Bright filtered light.",water:"Never let the compost fully dry.",humidity:"High humidity.",temperature:"Warm and stable.",feeding:"Very weak monthly feed.",soil:"Fine moisture-retentive compost.",tips:["It dislikes sudden changes.","Rainwater is helpful.","Cut back dead growth and keep moist for regrowth."],wateringDays:3},
  {id:"english-ivy",name:"English Ivy",scientific:"Hedera helix",emoji:"🍃",light:"Bright indirect light; some gentle sun.",water:"Water when the surface dries.",humidity:"Moderate humidity and airflow.",temperature:"Prefers cooler rooms.",feeding:"Monthly weak feed.",soil:"Free-draining houseplant compost.",tips:["Prune to keep compact.","Watch for spider mites.","Toxic if eaten."],wateringDays:6},
  {id:"philodendron",name:"Heartleaf Philodendron",scientific:"Philodendron hederaceum",emoji:"💚",light:"Bright indirect light; tolerates medium light.",water:"Water when the top few centimetres dry.",humidity:"Average to higher humidity.",temperature:"Warm indoor conditions.",feeding:"Monthly in spring and summer.",soil:"Chunky aroid mix.",tips:["Pinch or prune for bushier growth.","Can climb or trail.","Toxic if eaten."],wateringDays:8},
  {id:"syngonium",name:"Arrowhead Plant",scientific:"Syngonium podophyllum",emoji:"🍃",light:"Bright indirect light.",water:"Water when the top 2–3 cm dries.",humidity:"Moderate humidity.",temperature:"Warm indoor conditions.",feeding:"Monthly weak feed.",soil:"Airy houseplant compost.",tips:["Leaves change shape as the plant matures.","Prune to keep compact.","Toxic if eaten."],wateringDays:7},
  {id:"dracaena",name:"Dragon Tree",scientific:"Dracaena marginata",emoji:"🌴",light:"Bright indirect light; tolerates medium light.",water:"Let roughly half the compost dry.",humidity:"Average humidity.",temperature:"Warm and draught-free.",feeding:"Light monthly feed in growth.",soil:"Free-draining houseplant compost.",tips:["Filtered water can reduce brown tips.","Do not overwater.","Toxic to pets."],wateringDays:10},
  {id:"parlour-palm",name:"Parlour Palm",scientific:"Chamaedorea elegans",emoji:"🌴",light:"Medium to bright indirect light.",water:"Water when the top layer dries.",humidity:"Moderate humidity.",temperature:"Normal indoor warmth.",feeding:"Weak monthly feed in spring and summer.",soil:"Free-draining houseplant compost.",tips:["Avoid harsh direct sun.","It grows slowly.","Non-toxic to cats and dogs."],wateringDays:8},
  {id:"areca-palm",name:"Areca Palm",scientific:"Dypsis lutescens",emoji:"🌴",light:"Bright indirect light.",water:"Keep lightly moist but drained.",humidity:"Likes higher humidity.",temperature:"Warm and away from draughts.",feeding:"Monthly palm feed in growth.",soil:"Airy free-draining compost.",tips:["Brown tips can mean dry air or salts.","Rotate for even growth.","Do not leave standing in water."],wateringDays:6},
  {id:"croton",name:"Croton",scientific:"Codiaeum variegatum",emoji:"🍂",light:"Very bright indirect light with some gentle sun.",water:"Water when the top 2–3 cm dries.",humidity:"Likes humidity.",temperature:"Warm and very stable.",feeding:"Monthly feed in growth.",soil:"Rich free-draining compost.",tips:["Sudden changes can cause leaf drop.","Bright light keeps colours vivid.","Sap is irritating and plant is toxic."],wateringDays:6},
  {id:"fittonia",name:"Nerve Plant",scientific:"Fittonia albivenis",emoji:"🌿",light:"Medium to bright indirect light.",water:"Keep lightly and consistently moist.",humidity:"High humidity.",temperature:"Warm stable temperatures.",feeding:"Weak monthly feed.",soil:"Moisture-retentive airy mix.",tips:["It droops dramatically when thirsty.","Pinch tips for bushiness.","Excellent for terrariums."],wateringDays:4},
  {id:"pilea",name:"Chinese Money Plant",scientific:"Pilea peperomioides",emoji:"🪴",light:"Bright indirect light.",water:"Water when the top few centimetres dry.",humidity:"Average humidity.",temperature:"Normal indoor temperatures.",feeding:"Monthly weak feed.",soil:"Free-draining houseplant compost.",tips:["Rotate regularly.","Separate pups when established.","Drooping can mean thirst or excess water."],wateringDays:7},
  {id:"hoya",name:"Wax Plant",scientific:"Hoya carnosa",emoji:"🌸",light:"Bright indirect light with some gentle sun.",water:"Allow most of the compost to dry.",humidity:"Moderate humidity.",temperature:"Warm indoor conditions.",feeding:"Weak monthly feed in growth.",soil:"Chunky free-draining mix.",tips:["Do not remove old flower spurs.","Likes being slightly pot-bound.","Avoid frequent moves while budding."],wateringDays:11},
  {id:"venus-flytrap",name:"Venus Flytrap",scientific:"Dionaea muscipula",emoji:"🌱",light:"Full direct sun.",water:"Stand the pot in a shallow tray of rain or distilled water during growth.",humidity:"Average humidity with airflow.",temperature:"Needs a cool winter dormancy.",feeding:"Do not fertilise the compost.",soil:"Nutrient-poor carnivorous plant mix.",tips:["Never use tap water in hard-water areas.","Do not trigger traps for fun.","It needs winter dormancy to remain healthy."],wateringDays:2}
];

let plantUi={view:"collection",encyclopediaSearch:"",encyclopediaOpen:null};
function encyclopediaEntry(id,name){return PLANT_ENCYCLOPEDIA.find(x=>x.id===id)||PLANT_ENCYCLOPEDIA.find(x=>x.name.toLowerCase()===String(name||"").toLowerCase())}
function plantStatus(p){
  const guide=encyclopediaEntry(p.guideId||p.id,p.name);
  const threshold=Number(p.wateringDays)||guide?.wateringDays||5;
  if(!p.lastWatered) return {text:"Needs attention",className:"attention",icon:"🔔",days:null,threshold};
  const days=Math.floor((new Date(today()+"T12:00:00")-new Date(p.lastWatered+"T12:00:00"))/86400000);
  return days>=threshold?{text:`${days} days ago`,className:"attention",icon:"🔔",days,threshold}:{text:"All good",className:"good",icon:"🌿",days,threshold};
}
function plantProfileTab(){return data.plantProfileTab||"overview"}
function careGuideHtml(guide){
  if(!guide)return `<section class="card clean-card"><h2>No care guide linked yet</h2><p>Open the encyclopedia and choose the closest match for this plant.</p></section>`;
  return `<section class="card clean-card plant-care-guide">
    <div class="plant-guide-title"><div class="encyclopedia-icon">${guide.emoji}</div><div><span class="section-kicker">Built-in care guide</span><h2>${esc(guide.name)}</h2><p><i>${esc(guide.scientific)}</i></p></div></div>
    <div class="care-fact-grid">
      <div><span>☀️</span><small>Light</small><p>${esc(guide.light)}</p></div>
      <div><span>💧</span><small>Water</small><p>${esc(guide.water)}</p></div>
      <div><span>💨</span><small>Humidity</small><p>${esc(guide.humidity)}</p></div>
      <div><span>🌡️</span><small>Temperature</small><p>${esc(guide.temperature)}</p></div>
      <div><span>🌱</span><small>Feeding</small><p>${esc(guide.feeding)}</p></div>
      <div><span>🪴</span><small>Soil</small><p>${esc(guide.soil)}</p></div>
    </div>
    <div class="plant-tips"><h3>Good to know</h3>${guide.tips.map(t=>`<p>✨ ${esc(t)}</p>`).join("")}</div>
  </section>`;
}
function encyclopediaCard(g,owned){return `<article class="encyclopedia-card">
  <button type="button" class="encyclopedia-open" data-guide-open="${g.id}"><span>${g.emoji}</span><div><h2>${esc(g.name)}</h2><p>${esc(g.scientific)}</p><small>${esc(g.light.split(".")[0])}</small></div><b>›</b></button>
  ${owned?`<em class="owned-chip">✓ In my garden</em>`:`<button type="button" class="mini" data-add-guide="${g.id}">＋ Add to my garden</button>`}
</article>`}

function PlantsPage(){
  const attention=data.plants.filter(p=>plantStatus(p).className==="attention").length;
  const q=plantUi.encyclopediaSearch.toLowerCase();
  const guides=PLANT_ENCYCLOPEDIA.filter(g=>[g.name,g.scientific,g.light,g.water].join(" ").toLowerCase().includes(q));
  const opened=PLANT_ENCYCLOPEDIA.find(g=>g.id===plantUi.encyclopediaOpen);
  return shell(`${head("Garden","Your enchanted plant family")}
    <section class="plant-garden-hero card"><div><span class="section-kicker">🌸 Enchanted garden</span><h1>${plantUi.view==="collection"?"My garden":"Plant encyclopedia"}</h1><p>${plantUi.view==="collection"?"A little home for watering, photos and care notes.":"Care guidance that works even when LinaHub is offline."}</p></div><div class="blossom-branch" aria-hidden="true"><span>🌸</span><span>🌸</span><span>🌸</span></div></section>
    <div class="plant-main-tabs"><button class="${plantUi.view==="collection"?"active":""}" data-plant-view="collection">🪴 My garden</button><button class="${plantUi.view==="encyclopedia"?"active":""}" data-plant-view="encyclopedia">📖 Encyclopedia</button></div>
    ${plantUi.view==="collection"?`
      <div class="plant-search"><span>⌕</span><input id="plantSearch" placeholder="Search plants…"><span>${attention?`🔔 ${attention}`:"✓"}</span></div>
      <div class="plant-tile-grid" id="plantList">${data.plants.map(p=>{const s=plantStatus(p);return `<button type="button" class="plant-tile" data-route="plant" data-route-id="${esc(p.id)}" data-plant-name="${esc(p.name.toLowerCase())}"><div class="plant-tile-art">${p.photo?`<img src="${p.photo}" alt="${esc(p.name)}">`:`<span>${p.emoji}</span>`}</div><div class="plant-tile-copy"><h2>${esc(p.name)}</h2><p>${p.lastWatered?`Watered ${esc(formatDate(p.lastWatered))}`:"Not watered yet"}</p><em class="status-chip ${s.className}">${s.icon} ${s.text}</em></div></button>`}).join("")}</div>`:`
      <div class="plant-search"><span>⌕</span><input id="encyclopediaSearch" value="${esc(plantUi.encyclopediaSearch)}" placeholder="Search name or care need…"><span>📖 ${guides.length}</span></div>
      <div class="encyclopedia-actions"><button type="button" class="secondary" id="addCustomPlant">＋ Add a plant not listed</button></div><div class="encyclopedia-grid" id="encyclopediaGrid">${guides.map(g=>encyclopediaCard(g,data.plants.some(p=>(p.guideId||p.id)===g.id))).join("")||`<section class="card encyclopedia-empty"><p>No matching plants found.</p></section>`}</div>`}
    ${opened?`<div class="plant-guide-backdrop" data-close-guide><section class="plant-guide-modal"><button class="poke-detail-close" data-close-guide>×</button>${careGuideHtml(opened)}${data.plants.some(p=>(p.guideId||p.id)===opened.id)?"":`<button class="primary full-width" data-add-guide="${opened.id}">Add to my garden</button>`}</section></div>`:""}
  `,"plants");
}

function PlantProfilePage(){
  const p=data.plants.find(x=>x.id===routeId);if(!p)return PlantsPage();
  const history=[...(p.history||[])].sort().reverse(),status=plantStatus(p),active=plantProfileTab(),guide=encyclopediaEntry(p.guideId||p.id,p.name);
  return shell(`${head(p.name,"Plant profile","plants")}
    <section class="card plant-profile-head"><div class="plant-photo-large">${p.photo?`<img src="${p.photo}" alt="${esc(p.name)}">`:`<span>${p.emoji}</span>`}</div><div class="plant-profile-actions"><label class="secondary upload-label">📷 Add / change photo<input id="plantPhoto" type="file" accept="image/*" hidden></label><em class="status-chip ${status.className}">${status.icon} ${status.text}</em></div></section>
    <div class="profile-tabs" role="tablist" aria-label="Plant profile sections">${[["overview","Overview"],["care","Care"],["history","History"],["notes","Notes"]].map(([id,label])=>`<button type="button" role="tab" aria-selected="${active===id}" data-plant-tab="${id}" class="${active===id?"active":""}">${label}</button>`).join("")}</div>
    <div class="plant-tab-panel ${active==="overview"?"active":""}"><section class="care-summary"><div><small>Last watered</small><strong>${p.lastWatered?formatDate(p.lastWatered):"Not yet"}</strong></div><div><small>Waterings logged</small><strong>${history.length}</strong></div></section><section class="card clean-card"><span class="section-kicker">Overview</span><h2>Current care</h2><p>${p.lastWatered?`Last watered on ${formatDate(p.lastWatered)}.`:"No watering has been logged yet."}</p><p>${p.notes?esc(p.notes):"No personal care notes saved yet."}</p></section>${careGuideHtml(guide)}</div>
    <div class="plant-tab-panel ${active==="care"?"active":""}"><section class="card clean-card"><span class="section-kicker">Care</span><h2>Log watering</h2><div class="dated-action"><label class="date-picker-shell" aria-label="Watering date"><span>📅</span><input id="plantWaterDate" type="date" value="${today()}" max="${today()}"></label><button type="button" class="primary" id="waterPlant">💧 Log watering</button></div><p class="helper-text">Today is selected automatically. Open the calendar to record an earlier watering.</p></section>${careGuideHtml(guide)}</div>
    <div class="plant-tab-panel ${active==="history"?"active":""}"><section class="card clean-card"><span class="section-kicker">History</span><h2>Watering history</h2><div class="history-list">${history.length?history.map(d=>`<div class="history-row"><span>💧</span><span>${esc(formatDate(d))}</span><button type="button" class="icon-danger" data-water-delete="${esc(d)}" aria-label="Delete ${esc(formatDate(d))}">×</button></div>`).join(""):`<p>No watering history yet.</p>`}</div></section></div>
    <div class="plant-tab-panel ${active==="notes"?"active":""}"><section class="card clean-card"><span class="section-kicker">Notes</span><h2>Care notes</h2><textarea class="field plant-notes" rows="6" placeholder="Care notes, growth updates, anything you notice...">${esc(p.notes)}</textarea><button type="button" class="primary" id="savePlantNotes">Save notes</button></section></div>
  `,"plants");
}
function addEncyclopediaPlant(id){const g=PLANT_ENCYCLOPEDIA.find(x=>x.id===id);if(!g)return;if(data.plants.some(p=>(p.guideId||p.id)===id)){toast("That plant is already in your collection");return}data.plants.push({id:`${id}-${Date.now()}`,guideId:id,name:g.name,emoji:g.emoji,notes:"",lastWatered:"",history:[],photo:"",wateringDays:g.wateringDays});saveData();plantUi.encyclopediaOpen=null;plantUi.view="collection";render();toast(`${g.name} added to your garden 🌿`)}
function bindPlants(){
  document.querySelectorAll("[data-plant-view]").forEach(b=>b.onclick=()=>{plantUi.view=b.dataset.plantView;plantUi.encyclopediaOpen=null;render()});
  document.querySelector("#plantSearch")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("[data-plant-name]").forEach(tile=>tile.hidden=!tile.dataset.plantName.includes(q))});
  document.querySelector("#encyclopediaSearch")?.addEventListener("input",e=>{
    plantUi.encyclopediaSearch=e.target.value;
    const q=e.target.value.trim().toLowerCase();
    let visible=0;
    document.querySelectorAll(".encyclopedia-card").forEach(card=>{
      const match=!q||card.textContent.toLowerCase().includes(q);
      card.hidden=!match; if(match) visible++;
    });
    const count=e.target.closest(".plant-search")?.querySelector("span:last-child");
    if(count) count.textContent=`📖 ${visible}`;
    document.querySelector(".encyclopedia-empty")?.remove();
    if(!visible){const empty=document.createElement("section");empty.className="card encyclopedia-empty";empty.innerHTML="<p>No matching plants found. You can still add it as a custom plant.</p>";document.querySelector("#encyclopediaGrid")?.append(empty)}
  });
  document.querySelector("#addCustomPlant")?.addEventListener("click",()=>{
    const name=prompt("Plant name"); if(!name?.trim())return;
    const emoji=prompt("Choose an icon for it", "🌿")||"🌿";
    const id=`custom-${Date.now()}`;
    data.plants.push({id,name:name.trim().slice(0,60),emoji:emoji.trim().slice(0,4)||"🌿",notes:"",lastWatered:"",history:[],photo:"",guideId:"",wateringDays:7});
    saveData(); plantUi.view="collection"; render(); toast(`${name.trim()} added to your garden 🌿`);
  });
  document.querySelectorAll("[data-guide-open]").forEach(b=>b.onclick=()=>{plantUi.encyclopediaOpen=b.dataset.guideOpen;render()});
  document.querySelectorAll("[data-close-guide]").forEach(b=>b.onclick=e=>{if(e.target===b||b.classList.contains("poke-detail-close")){plantUi.encyclopediaOpen=null;render()}});
  document.querySelectorAll("[data-add-guide]").forEach(b=>b.onclick=()=>addEncyclopediaPlant(b.dataset.addGuide));
  document.querySelectorAll("[data-plant-tab]").forEach(button=>button.addEventListener("click",()=>{data.plantProfileTab=button.dataset.plantTab;saveData();render()}));
  document.querySelector("#waterPlant")?.addEventListener("click",()=>{const p=data.plants.find(x=>x.id===routeId);if(!p)return;const date=document.querySelector("#plantWaterDate")?.value||today();if(date>today()){toast("Choose today or an earlier date");return}p.history=Array.isArray(p.history)?p.history:[];if(!p.history.includes(date))p.history.push(date);p.history.sort();p.lastWatered=p.history[p.history.length-1]||"";saveData();toast(`${p.name} watering logged 💧`);render()});
  document.querySelectorAll("[data-water-delete]").forEach(button=>button.addEventListener("click",()=>{const p=data.plants.find(x=>x.id===routeId);if(!p)return;p.history=(p.history||[]).filter(date=>date!==button.dataset.waterDelete);p.history.sort();p.lastWatered=p.history[p.history.length-1]||"";saveData();toast("Watering entry removed");render()}));
  document.querySelector("#savePlantNotes")?.addEventListener("click",()=>{const p=data.plants.find(x=>x.id===routeId);if(!p)return;p.notes=document.querySelector(".plant-notes").value;saveData();toast("Plant notes saved 🌿")});
  document.querySelector("#plantPhoto")?.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const p=data.plants.find(x=>x.id===routeId);if(!p)return;p.photo=reader.result;saveData();toast("Plant photo saved 📷");render()};reader.readAsDataURL(file)});
}
